In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("Loan_default.csv")

In [6]:
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default,Loan Date (DD/MM/YYYY)
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0,10/15/2018
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0,3/25/2016
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1,11/11/2013
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0,6/22/2017
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0,6/9/2014

In [7]:
df.shape

(255347, 19)

In [8]:
df.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner', 'Default',
       'Loan Date (DD/MM/YYYY)'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 19 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   LoanID                  255347 non-null  object
 1   Age                     255347 non-null  int64
 2   Income                  255347 non-null  int64
 3   LoanAmount              255347 non-null  int64
 4   CreditScore             255347 non-null  int64
 5   MonthsEmployed          255347 non-null  int64
 6   NumCreditLines          255347 non-null  int64
 7   InterestRate            255347 non-null  float64
 8   LoanTerm                255347 non-null  int64
 9   DTIRatio                255347 non-null  float64
 10  Education               255347 non-null  object
 11  EmploymentType          255347 non-null  object
 12  MaritalStatus           255347 non-null  object
 13  HasMortgage             255347 non-null  object
 14  HasDependents           255347 non-null  object
 15  LoanPurpose             255347 non-null  object
 16  HasCoSigner             255347 non-null  object
 17  Default                 255347 non-null  int64
 18  Loan Date (DD/MM/YYYY)  255347 non-null  object
dtypes: float64(2), int64(8), object(9)
memory usage: 37.0+ MB

In [10]:
df.isnull().sum()

LoanID                    0
Age                       0
Income                    0
LoanAmount                0
CreditScore               0
MonthsEmployed            0
NumCreditLines            0
InterestRate              0
LoanTerm                  0
DTIRatio                  0
Education                 0
EmploymentType            0
MaritalStatus             0
HasMortgage               0
HasDependents             0
LoanPurpose               0
HasCoSigner               0
Default                   0
Loan Date (DD/MM/YYYY)    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["LoanID"].duplicated().sum()

np.int64(0)

In [13]:
df["Default"].value_counts()

Default
0    225694
1     29653
Name: count, dtype: int64

In [14]:
df["Default"].value_counts(normalize=True) * 100

Default
0    88.387175
1    11.612825
Name: proportion, dtype: float64

In [15]:
categorical_columns = df.select_dtypes(include="object").columns
categorical_columns

Index(['LoanID', 'Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage',
       'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Loan Date (DD/MM/YYYY)'],
      dtype='object')

In [16]:
categorical_columns = [
    "Education",
    "EmploymentType",
    "MaritalStatus",
    "HasMortgage",
    "HasDependents",
    "LoanPurpose",
    "HasCoSigner"
]

for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].unique())

Education:
["Bachelor's" "Master's" 'High School' 'PhD']

EmploymentType:
['Full-time' 'Unemployed' 'Self-employed' 'Part-time']

MaritalStatus:
['Divorced' 'Married' 'Single']

HasMortgage:
['Yes' 'No']

HasDependents:
['Yes' 'No']

LoanPurpose:
['Other' 'Auto' 'Business' 'Home' 'Education']

HasCoSigner:
['Yes' 'No']

In [17]:
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

df[numerical_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Age,255347.0,43.498306,14.990258,18.0,31.00,43.00,56.00,69.0
Income,255347.0,82499.304597,38963.013729,15000.0,48825.50,82466.00,116219.00,149999.0
LoanAmount,255347.0,127578.865512,70840.706142,5000.0,66156.00,127556.00,188985.00,249999.0
CreditScore,255347.0,574.264346,158.903867,300.0,437.00,574.00,712.00,849.0
MonthsEmployed,255347.0,59.541976,34.643376,0.0,30.00,60.00,90.00,119.0
NumCreditLines,255347.0,2.501036,1.117018,1.0,2.00,2.00,3.00,4.0
InterestRate,255347.0,13.492773,6.636443,2.0,7.77,13.46,19.25,25.0
LoanTerm,255347.0,36.025894,16.969330,12.0,24.00,36.00,48.00,60.0
DTIRatio,255347.0,0.500212,0.230917,0.1,0.30,0.50,0.70,0.9
Default,255347.0,0.116128,0.320379,0.0,0.00,0.00,0.00,1.0

In [18]:
df["Loan Date (DD/MM/YYYY)"].head(10)

0    10/15/2018
1     3/25/2016
2    11/11/2013
3     6/22/2017
4      6/9/2014
5     2/16/2018
6     8/13/2017
7     4/11/2014
8    11/23/2015
9    12/12/2018
Name: Loan Date (DD/MM/YYYY), dtype: object

In [19]:
df["Loan Date (DD/MM/YYYY)"].nunique()

2191